In [1]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]

In [5]:
m = [v, v, v]

In [6]:
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
m[1][0]

0.5

In [9]:
v1 = [ 0.5 , 1.5]
v2 = [1,2]
m= [v1,v2]

In [11]:
c = [m,m]

In [12]:
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [13]:
c[1][1][0]

1

In [14]:
v[0]='Pyhton'

In [15]:
v

['Pyhton', 0.75, 1.0, 1.5, 2.0]

In [17]:
m = [v, v, v]

In [18]:
m

[['Pyhton', 0.75, 1.0, 1.5, 2.0],
 ['Pyhton', 0.75, 1.0, 1.5, 2.0],
 ['Pyhton', 0.75, 1.0, 1.5, 2.0]]

In [19]:
v[0]='Alkan'

In [20]:
m

[['Alkan', 0.75, 1.0, 1.5, 2.0],
 ['Alkan', 0.75, 1.0, 1.5, 2.0],
 ['Alkan', 0.75, 1.0, 1.5, 2.0]]

In [22]:
# The referance's object changes so our derived object changes, too
# We can use deepcopy function to avoid this
from copy import deepcopy

In [23]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [27]:
m= 3 * [deepcopy(v)]

In [28]:
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [29]:
v[0]= 'Pyhton'

In [32]:
m # Nothing changed

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [31]:
# ARRAYS WITH NUMPY
# numpy.ndarray, which has been built with the specific goal
# of handling n-dimensional arrays both conveniently and efficiently

In [33]:
import numpy as np

In [34]:
a = np.array([0, 0.5 , 1.0, 1.5, 2.0])

In [35]:
type(a)

numpy.ndarray

In [36]:
a[:2] #indexing as with list objects in 1 dimension

array([0. , 0.5])

In [40]:
a.sum()

5.0

In [41]:
a.std() 

0.7071067811865476

In [42]:
a.cumsum() #running cumulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

In [44]:
a*2 #vectoral operations

array([0., 1., 2., 3., 4.])

In [45]:
a**2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [46]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [47]:
b=np.array([a,a*2])

In [48]:
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [51]:
b[0]

array([0. , 0.5, 1. , 1.5, 2. ])

In [52]:
b[0,2]

1.0

In [53]:
b.sum()

15.0

In [54]:
b.sum(axis=0)

array([0. , 1.5, 3. , 4.5, 6. ])

In [55]:
b.sum(axis=1)

array([ 5., 10.])

In [57]:
# numpy.ndarray objects
# instantiated first to populate them later with results generated during the execution of
# code

In [63]:
c= np.zeros((2,3,4), dtype='i', order='C') # also, n.ones, dtype = int or str

In [64]:
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [71]:
d= np.ones_like(c, dtype='float', order= 'C')

In [72]:
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [73]:
# pure Python approach to generalize (I,I) matrix columnd with random numbers
import random
I=5000
%time mat =  [[random.gauss(0,1) for j in range(I)] for i in range(I)]

Wall time: 19.8 s


In [75]:
# faster approach with np.random.standard_normal
%time mat = np.random.standard_normal((I,I))

Wall time: 1.47 s


In [81]:
# STRUCTURED ARRAYS
# NumPy provides structured arrays that allow us to have different NumPy data
# types per column
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
            ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0,1)),
            ('Jones', 53, 1.72, (2,2))], dtype=dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [84]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [85]:
s['Height'].mean()

1.7750001

In [86]:
s[1]['Age']

53