In [1]:
# Vectorization of Code
import numpy as np

In [2]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))

In [5]:
r+s

array([[-0.65073597, -0.97960196, -0.57440784],
       [ 1.31726573,  0.65422273,  0.02481705],
       [-0.64485184, -0.85605653, -3.31205589],
       [-0.63960748,  1.76930289,  2.17426854]])

In [6]:
2*r + 3

array([[ 2.38580546,  0.83115107,  3.29126101],
       [ 5.68820034,  4.52936108,  5.33392257],
       [ 3.37356946, -0.17859629,  0.81473118],
       [ 0.58079474,  5.92759553,  4.03479663]])

In [7]:
s = np.random.standard_normal(3) # no need for the exact same shape

In [13]:
s + r

array([[-1.74123522, -1.67449327,  1.81210799],
       [-0.09003778,  0.17461174,  2.83343877],
       [-1.24735321, -2.17936695,  0.57384307],
       [-2.64374057,  0.87372896,  2.18387579]])

In [14]:
s = np.random.standard_normal(4) 

In [16]:
r+s # This broadcasts the one-dimensional array of size 3 to a shape of (4, 3). The same does
    #not work, for example, with a one-dimensional array of size 4

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [17]:
r.transpose() + s

array([[-0.72480274, -0.00609034,  0.59514546, -2.34982491],
       [-1.50212994, -0.58550997, -1.18093742,  0.32357548],
       [-0.27207497, -0.18322923, -0.68427369, -0.62282397]])

In [18]:
np.shape(r.T)

(3, 4)

In [19]:
np.shape(r)

(4, 3)

In [20]:
# custom-defined Python functions work with numpy.ndarrays as well
def f(x):
    return 3*x + 5

In [21]:
f(0.5)

6.5

In [22]:
f(r)

array([[4.07870819, 1.7467266 , 5.43689151],
       [9.03230051, 7.29404163, 8.50088386],
       [5.56035419, 0.23210557, 1.72209676],
       [1.37119211, 9.39139329, 6.55219494]])

In [23]:
# When working with arrays, one has to take care to call the right functions on the respective
# objects. For example, the sin function from the standard math module of
# Python does not work with NumPy arrays:
import math
math.sin(r)

TypeError: only size-1 arrays can be converted to Python scalars

In [26]:
# The function is designed to handle, for example, float objects—i.e., single numbers,
# not arrays. NumPy provides the respective counterparts
np.sin(r) # array as input

array([[-0.30229299, -0.88403454,  0.14511629],
       [ 0.97441428,  0.69230651,  0.91956079],
       [ 0.18570052, -0.99982885, -0.88784221],
       [-0.93547565,  0.99428111,  0.49462067]])

In [27]:
np.sin(np.pi)  #float as input

1.2246467991473532e-16

In [79]:
x = np.random.standard_normal((5, 4))
y = 2*x + 3 #linear equation
C = np.array((x,y))
F = np.array((x,y), order = 'F')
x= 0.0; y = 0.0 #memory cleanup

In [80]:
C.round(2)

array([[[ 0.86,  1.09, -1.42,  2.03],
        [ 0.03, -0.96, -0.18, -1.32],
        [ 0.63, -0.64,  1.76,  0.59],
        [-2.64,  1.3 ,  0.42, -1.2 ],
        [-0.08, -0.24,  0.02, -0.01]],

       [[ 4.72,  5.19,  0.16,  7.06],
        [ 3.06,  1.09,  2.64,  0.36],
        [ 4.27,  1.72,  6.53,  4.19],
        [-2.28,  5.61,  3.85,  0.6 ],
        [ 2.85,  2.53,  3.04,  2.99]]])

In [81]:
F.round(2)

array([[[ 0.86,  1.09, -1.42,  2.03],
        [ 0.03, -0.96, -0.18, -1.32],
        [ 0.63, -0.64,  1.76,  0.59],
        [-2.64,  1.3 ,  0.42, -1.2 ],
        [-0.08, -0.24,  0.02, -0.01]],

       [[ 4.72,  5.19,  0.16,  7.06],
        [ 3.06,  1.09,  2.64,  0.36],
        [ 4.27,  1.72,  6.53,  4.19],
        [-2.28,  5.61,  3.85,  0.6 ],
        [ 2.85,  2.53,  3.04,  2.99]]])

(2, 5, 10000000)